name: Build, Test & Deploy Cart Service

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Job 1 : Vérification des dépendances
  check-dependencies:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

  # Job 2 : Exécution des tests (dépend du job des dépendances)
  run-tests:
    runs-on: ubuntu-22.04
    needs: check-dependencies
    steps:
      - name: Run Tests
        env:
          PORT: ${{ secrets.PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_POOL_MAX: ${{ secrets.DB_POOL_MAX }}
          DB_POOL_MIN: ${{ secrets.DB_POOL_MIN }}
          DB_POOL_IDLE: ${{ secrets.DB_POOL_IDLE }}
          DB_POOL_ACQUIRE: ${{ secrets.DB_POOL_ACQUIRE }}
        run: npx vitest run

  # Job 3 : Construction du service (dépend des tests)
  build-service:
    runs-on: ubuntu-22.04
    needs: run-tests
    steps:
      - name: Build Service
        run: npm run build || echo "No build step needed"

  # Job 4 : Publication sur Docker (seulement sur la branche main)
  publish-on-docker:
    needs: build-service
    if: github.ref == 'refs/heads/main'
    uses: Breizhsport-2025-cube-3/breizhsport-infra/.github/workflows/publish_on_docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-cart:develop
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
